# Generated by Django 5.1.3 on 2024-12-29 12:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='school',
        ),
        migrations.AddField(
            model_name='student',
            name='uid',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atendance',
            name='status',
            field=models.CharField(choices=[('O', 'On Time'), ('L', 'Late'), ('N', 'Not Attended'), ('E', 'Excused'), ('L', 'Left Early')], max_length=1),
        ),
    ]
