# Generated by Django 5.1.3 on 2024-12-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_clase_school_student_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='school',
        ),
        migrations.AddField(
            model_name='instructor',
            name='clases',
            field=models.ManyToManyField(related_name='instructors', to='school.clase'),
        ),
    ]
