# Generated by Django 5.1.3 on 2024-12-31 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_remove_student_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendance',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atendance',
            name='status',
            field=models.CharField(choices=[('O', 'On Time'), ('L', 'Late'), ('N', 'Not Attended'), ('E', 'Excused'), ('T', 'Left Early')], max_length=1),
        ),
    ]
