# Generated by Django 5.1.3 on 2024-12-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_atendance_observations_alter_atendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
