# Generated by Django 5.1.3 on 2024-12-31 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_remove_student_id_alter_student_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendances', to='school.student'),
        ),
    ]
