# Generated by Django 5.1.3 on 2025-01-03 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_atendance_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='clase',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='user',
        ),
        migrations.AddField(
            model_name='announcement',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='school.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='tutor_phone',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
