# Generated by Django 5.1.3 on 2025-01-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_remove_announcement_clase_remove_announcement_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.BigIntegerField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
