# Generated by Django 5.1.3 on 2025-01-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_alter_student_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendance',
            name='attendance_type',
            field=models.CharField(choices=[('A', 'Automatic'), ('M', 'Manual')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
