# Generated by Django 5.1.3 on 2025-01-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_tutor_can_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='created_by',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
