# Generated by Django 5.1.3 on 2025-01-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_announcement_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
