# Generated by Django 5.1.3 on 2025-01-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_alter_announcement_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendance',
            name='kind',
            field=models.CharField(choices=[('I', 'Entrance'), ('O', 'Exit')], default='I', max_length=1),
        ),
    ]
