# Generated by Django 5.1.3 on 2025-01-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='clases',
            field=models.ManyToManyField(related_name='assistants', to='school.clase'),
        ),
    ]
