# Generated by Django 5.1.3 on 2025-01-25 11:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_student_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendance',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
