# Generated by Django 5.1.3 on 2025-01-30 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_health_information_insurance_language_religion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='health_information',
            name='student',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='health_info', to='school.student'),
            preserve_default=False,
        ),
    ]
