# Generated by Django 5.1.3 on 2025-01-30 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0028_student_main_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='second_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_students', to='school.language'),
        ),
        migrations.AlterField(
            model_name='student',
            name='main_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_students', to='school.language'),
        ),
    ]
