# Generated by Django 5.1.3 on 2025-01-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0029_student_second_language_alter_student_main_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='insurance',
            field=models.CharField(blank=True, choices=[('C', 'Catholic'), ('E', 'Evangelic'), ('J', 'Jewish'), ('I', 'Muslim'), ('B', 'Buddhist'), ('M', 'Mormon'), ('T', 'Jehovah'), ('R', 'Christian'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='main_language',
            field=models.CharField(choices=[('S', 'Spanish'), ('E', 'English'), ('Q', 'Quechua'), ('A', 'Aymara')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_language',
            field=models.CharField(blank=True, choices=[('S', 'Spanish'), ('E', 'English'), ('Q', 'Quechua'), ('A', 'Aymara')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(choices=[('C', 'Catholic'), ('E', 'Evangelic'), ('J', 'Jewish'), ('I', 'Muslim'), ('B', 'Buddhist'), ('M', 'Mormon'), ('T', 'Jehovah'), ('R', 'Christian'), ('O', 'Other')], default='C', max_length=1),
        ),
        migrations.DeleteModel(
            name='Insurance',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Religion',
        ),
    ]
