# Generated by Django 5.1.3 on 2025-02-02 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0033_alter_emergency_contact_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency_contact',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact', to='school.student'),
        ),
    ]
