# Generated by Django 5.1.3 on 2025-02-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0034_alter_emergency_contact_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tutor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
