# Generated by Django 5.1.3 on 2025-02-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0038_tutor_lives_with_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='health_information',
            name='handycap',
            field=models.CharField(choices=[('V', 'Visual'), ('A', 'Autism'), ('M', 'Motor'), ('C', 'Cognitive'), ('P', 'Psychological'), ('H', 'Hearing-Vision'), ('O', 'Other'), ('N', 'None')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='health_information',
            name='psicopedagogic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='health_information',
            name='saanee',
            field=models.BooleanField(default=False),
        ),
    ]
