# Generated by Django 5.1.3 on 2025-02-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0039_health_information_handycap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='other_insurance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='insurance',
            field=models.CharField(blank=True, choices=[('E', 'Essalud'), ('P', 'Private'), ('S', 'SIS'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
