# Generated by Django 5.1.3 on 2025-02-20 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0041_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='school.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clase',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='school.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='school.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to='school.school'),
            preserve_default=False,
        ),
    ]
