# Generated by Django 5.1.3 on 2025-02-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0044_school_address_school_email_school_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='health_information',
            name='hsndyCap_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
