# Generated by Django 5.1.3 on 2025-02-27 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0047_alter_area_id_alter_capacity_id_alter_competence_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignature',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignatures', to='school.instructor'),
        ),
    ]
