# Generated by Django 5.1.3 on 2025-02-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0048_alter_assignature_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='capacities',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='competences',
        ),
        migrations.AddField(
            model_name='activity',
            name='capacities',
            field=models.ManyToManyField(related_name='activities', to='school.capacity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='competences',
            field=models.ManyToManyField(related_name='activities', to='school.competence'),
        ),
    ]
