# Generated by Django 5.1.3 on 2025-03-01 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0049_remove_activity_capacities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartergrade',
            name='assignature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='averages', to='school.assignature'),
        ),
    ]
