# Generated by Django 5.1.3 on 2025-03-01 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0050_alter_quartergrade_assignature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='assignature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='school.assignature'),
        ),
    ]
