# Generated by Django 5.1.3 on 2025-03-02 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0051_alter_activity_assignature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartergrade',
            name='competence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='averages', to='school.competence'),
        ),
    ]
