# Generated by Django 5.1.3 on 2025-03-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0052_alter_quartergrade_competence'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tutor_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
