# Generated by Django 5.1.3 on 2025-03-12 08:20

import school.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0054_alter_activity_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.BigIntegerField(default=school.models.Student.generate_uid, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
