# Generated by Django 5.1.3 on 2025-03-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0055_student_dni_alter_student_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
