# Generated by Django 5.1.3 on 2025-03-17 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0056_instructor_email_instructor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendance',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='atendances', to='school.school'),
            preserve_default=False,
        ),
    ]
