# Generated by Django 5.1.3 on 2025-03-17 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0057_atendance_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendance',
            name='school',
        ),
    ]
