# Generated by Django 5.1.3 on 2025-03-19 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0057_announcement_announcement_type_announcement_school_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='assignature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='school.assignature'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='school.clase'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='visibility_level',
            field=models.CharField(choices=[('G', 'General'), ('C', 'Clase'), ('A', 'Assignature'), ('P', 'Personal')], default='G', max_length=1),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_announcements', to='school.student'),
        ),
    ]
