# Generated by Django 5.1.3 on 2025-03-19 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0058_announcement_assignature_announcement_clase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='school.student'),
        ),
    ]
