# Generated by Django 5.1.3 on 2025-03-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0059_alter_announcement_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='student',
        ),
        migrations.AddField(
            model_name='announcement',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, related_name='announcements', to='school.student'),
        ),
    ]
