# Generated by Django 5.1.3 on 2025-03-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0060_remove_announcement_student_announcement_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='clase',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='student',
        ),
        migrations.AddField(
            model_name='announcement',
            name='clases',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='school.clase'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='school.student'),
        ),
    ]
