# Generated by Django 5.1.3 on 2025-03-24 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0063_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorReadAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_agendas', to='school.tutor')),
            ],
        ),
    ]
