# Generated by Django 5.1.3 on 2025-03-24 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0064_tutorreadagenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorreadagenda',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='read_agendas', to='school.student'),
            preserve_default=False,
        ),
    ]
