# Generated by Django 5.1.3 on 2025-03-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0065_tutorreadagenda_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorreadagenda',
            name='agenda_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
