# Generated by Django 5.1.3 on 2025-04-22 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0071_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='grade_level',
        ),
        migrations.AddField(
            model_name='lesson',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='school.clase'),
            preserve_default=False,
        ),
    ]
