# Generated by Django 5.1.3 on 2025-04-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0072_remove_lesson_grade_level_lesson_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
