# Generated by Django 5.1.3 on 2025-04-25 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0073_activity_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='content',
        ),
        migrations.AddField(
            model_name='activity',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='school.lesson'),
        ),
    ]
