# Generated by Django 5.1.3 on 2025-04-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0074_remove_activity_content_activity_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'First Quarter'), ('Q2', 'Second Quarter'), ('Q3', 'Third Quarter'), ('Q4', 'Fourth Quarter')], default='Q1', max_length=2),
        ),
    ]
