# Generated by Django 5.1.3 on 2025-04-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0075_lesson_quarter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='lesson',
        ),
        migrations.AddField(
            model_name='activity',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='activities', to='school.lesson'),
        ),
    ]
