# Generated by Django 5.1.3 on 2025-05-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0076_remove_activity_lesson_activity_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Paid'), ('N', 'Not Paid')], default='P', max_length=1),
        ),
    ]
