# Generated by Django 5.1.3 on 2025-05-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0077_school_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='automatic_late',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
