# Generated by Django 5.1.3 on 2025-05-04 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0078_school_automatic_late'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='automatic_not_show',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AddField(
            model_name='school',
            name='automatic_on_time_out',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
    ]
