# Generated by Django 5.1.3 on 2025-06-06 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0079_school_automatic_not_show_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='automatic_late_iitial',
            field=models.TimeField(default=datetime.time(8, 50)),
        ),
    ]
