# Generated by Django 5.1.3 on 2025-06-06 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0080_school_automatic_late_iitial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='automatic_late_iitial',
            new_name='automatic_late_initial',
        ),
    ]
