from django.contrib import admin
from . import models

admin.site.register(models.Clase)
admin.site.register(models.Instructor)
admin.site.register(models.Assistant)
admin.site.register(models.Student)
admin.site.register(models.Tutor)
admin.site.register(models.Atendance)
admin.site.register(models.Announcement)
admin.site.register(models.School)
admin.site.register(models.Manager)
admin.site.register(models.Health_Information)
admin.site.register(models.Emergency_Contact)
admin.site.register(models.Birth_Info)
admin.site.register(models.Area)
admin.site.register(models.Competence)
admin.site.register(models.Capacity)
admin.site.register(models.Assignature)
admin.site.register(models.Category)
admin.site.register(models.Grade)
admin.site.register(models.QuarterGrade)
admin.site.register(models.Activity)
admin.site.register(models.Developer)
admin.site.register(models.TutorReadAgenda)
admin.site.register(models.TutorContact)
admin.site.register(models.TutorAuthInfo)
admin.site.register(models.WhatsappMessage)
admin.site.register(models.Balance)
admin.site.register(models.Lesson)