# Generated by Django 5.1.3 on 2025-03-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
