# Generated by Django 5.1.3 on 2025-01-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pushsubscription',
            old_name='p256dh_key',
            new_name='p256dh',
        ),
    ]
