# Generated by Django 5.1.3 on 2025-01-11 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_rename_p256dh_key_pushsubscription_p256dh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pushsubscription',
            old_name='auth_key',
            new_name='auth',
        ),
    ]
